"""
build_report.py — Stage 8. Self-contained, auto-reproducible visual report.

Produces a SINGLE standalone results/report.html that opens in any browser with no
network or external files: Plotly is inlined once, all tables/charts are regenerated
from data/*.csv. Re-running this script after new data refreshes the whole report —
the same single-source-of-truth as the LaTeX tables.

Sections: corpus summary | descriptive stats | RQ1 (structure) | RQ2 (change-proneness)
          | statistical tests | CK validation | thresholds vs Filo et al.

Usage: python analysis/build_report.py
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
RESULTS = ROOT / "results"
RESULTS.mkdir(exist_ok=True)

PATTERNS = ["MVP", "MVVM", "MVI"]
COLORS = {"MVP": "#8ecae6", "MVVM": "#ffb703", "MVI": "#90be6d"}
# Filo et al. (2024) "good/regular" upper thresholds used as comparison baselines.
FILO = {"CBO": 9, "LCOM": 20, "WMC": 22}


def read(name: str) -> pd.DataFrame:
    p = DATA / name
    return pd.read_csv(p) if p.exists() else pd.DataFrame()


def df_to_html(df: pd.DataFrame) -> str:
    if df.empty:
        return "<p><em>No data.</em></p>"
    return df.to_html(index=False, classes="tbl", border=0, float_format=lambda x: f"{x:.3f}")


def box(df: pd.DataFrame, col: str, title: str, first: bool) -> str:
    if col not in df.columns:
        return ""
    fig = go.Figure()
    for p in PATTERNS:
        s = df.loc[df.pattern == p, col].dropna()
        if len(s):
            fig.add_trace(go.Box(y=s, name=p, marker_color=COLORS[p], boxpoints="all",
                                 jitter=0.4, pointpos=0))
    if col in FILO:
        fig.add_hline(y=FILO[col], line_dash="dot", line_color="red",
                      annotation_text=f"Filo threshold = {FILO[col]}")
    fig.update_layout(title=title, height=360, margin=dict(t=40, b=20, l=40, r=10),
                      showlegend=False, template="plotly_white")
    return fig.to_html(full_html=False,
                       include_plotlyjs="inline" if first else False)


def corpus_bar(corpus: pd.DataFrame) -> str:
    if corpus.empty:
        return ""
    inc = corpus[corpus.get("included", True) == True] if "included" in corpus else corpus
    counts = inc["confirmed_pattern"].value_counts().reindex(PATTERNS).fillna(0) \
        if "confirmed_pattern" in inc else pd.Series(dtype=int)
    fig = px.bar(x=counts.index, y=counts.values,
                 color=counts.index, color_discrete_map=COLORS,
                 labels={"x": "Pattern", "y": "Repositories"})
    fig.update_layout(title="Confirmed corpus by pattern", height=320, showlegend=False,
                      template="plotly_white", margin=dict(t=40, b=20))
    return fig.to_html(full_html=False, include_plotlyjs=False)


TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>MVP/MVVM/MVI — Empirical Results</title>
<style>
 body{{font-family:system-ui,Segoe UI,Arial,sans-serif;max-width:1000px;margin:2rem auto;
      padding:0 1rem;color:#222;line-height:1.5}}
 h1{{border-bottom:3px solid #023047;padding-bottom:.3rem}}
 h2{{margin-top:2.2rem;color:#023047;border-left:5px solid #ffb703;padding-left:.5rem}}
 .tbl{{border-collapse:collapse;margin:1rem 0;font-size:.9rem}}
 .tbl th,.tbl td{{border:1px solid #ccc;padding:.35rem .6rem;text-align:right}}
 .tbl th:first-child,.tbl td:first-child{{text-align:left}}
 .tbl tr:nth-child(even){{background:#f7f7f7}}
 .grid{{display:grid;grid-template-columns:1fr 1fr;gap:1rem}}
 .note{{background:#eef6fb;border-left:4px solid #219ebc;padding:.6rem .9rem;font-size:.9rem}}
 footer{{margin-top:3rem;color:#888;font-size:.8rem;border-top:1px solid #ddd;padding-top:1rem}}
</style></head><body>
<h1>Empirical Comparison of MVP, MVVM &amp; MVI</h1>
<p class="note">Android code-maintainability study via repository mining. Every figure and
table below is generated from <code>data/*.csv</code>; re-run <code>analysis/build_report.py</code>
to refresh. Analysis unit = one repository (per-repo medians). Statistical tests:
Kruskal–Wallis + pairwise Mann–Whitney (Holm), Cliff's δ effect size, α = 0.05.</p>

<h2>1. Corpus</h2>
{corpus_bar}
{corpus_table}

<h2>2. Descriptive statistics (per-repo medians)</h2>
{desc_table}

<h2>3. RQ1 — Presentation-layer structure</h2>
<div class="grid">{rq1_boxes}</div>
{rq1_tests}

<h2>4. RQ2 — Change-proneness</h2>
<div class="grid">{rq2_boxes}</div>
{rq2_tests}

<h2>5. Construct-validity check vs CK</h2>
<p>Spearman correlation between our tree-sitter extractor and CK on shared Java classes
(ρ ≥ 0.7 indicates the metrics capture the same construct):</p>
{ck_table}

<footer>Generated by build_report.py · self-contained (Plotly inlined) · MVP/MVVM/MVI study</footer>
</body></html>"""


def main() -> int:
    corpus = read("corpus.csv")
    metrics = read("metrics_per_repo.csv")
    churn = read("churn.csv")
    if not metrics.empty and not churn.empty:
        metrics = metrics.merge(churn, on="repo", how="left")

    rq1_boxes, first = [], True
    for col, t in [("CBO", "CBO"), ("LCOM", "LCOM-HS"), ("WMC", "WMC")]:
        html = box(metrics, col, t, first)
        if html:
            rq1_boxes.append(html)
            first = False
    rq2_boxes = []
    for col, t in [("median_commits_per_month", "Commits / month"),
                   ("median_churn_per_sloc", "Churn / SLOC")]:
        html = box(metrics, col, t, False)
        if html:
            rq2_boxes.append(html)

    page = TEMPLATE.format(
        corpus_bar=corpus_bar(corpus),
        corpus_table=df_to_html(corpus),
        desc_table=df_to_html(read("descriptive.csv")),
        rq1_boxes="".join(rq1_boxes) or "<p><em>No metrics yet.</em></p>",
        rq1_tests=df_to_html(read("stats_rq1.csv")),
        rq2_boxes="".join(rq2_boxes) or "<p><em>No churn data yet.</em></p>",
        rq2_tests=df_to_html(read("stats_rq2.csv")),
        ck_table=df_to_html(read("ck_validation.csv")),
    )
    out = RESULTS / "report.html"
    out.write_text(page, encoding="utf-8")
    print(f"Wrote {out} ({out.stat().st_size // 1024} KB, self-contained)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
